
services:
  db:
    image: postgres:16-alpine
    container_name: movie-chat-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-movie_chat}
    ports:
      - "${DB_PORT:-5422}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: movie-chat-app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-movie_chat}?schema=public
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET:-un_secreto_muy_seguro}
      PORT: ${APP_PORT:-3003}
    ports:
      - "${APP_PORT:-3003}:${APP_PORT:-3003}"
      - "${APP_PORT:-3003}:${APP_PORT:-3003}"

volumes:
  postgres_data:
